### ISSUE TITLE
How i can use sendgrid templates with this gem?

### ISSUE THREAD

**Issue by Malstrom** [PavelTyk/sendgrid-rails#17]

**Comment by phthhieu** [comment]
👍

**Comment by PavelTyk** [comment]
Currently I do not have support for this. Anyone want to do a pull request?

**Comment by phthhieu** [comment]
@PavelTyk Please take a look https://github.com/PavelTyk/sendgrid-rails/pull/20

**Comment by paveltyk** [comment]
released as v3.1.0
