### ISSUE TITLE
Unique Arguments in Sendgrid mail

### ISSUE THREAD

**Issue by zeeshangulzar** [PavelTyk/sendgrid-rails#31]
I am implementing the webhooks and want to add my arguments which i can recieve in events webhook. I believe we are using v2 so i need to send my arguments in **unique_args** parameter. Please if you can guide how i can add this parameter?

https://sendgrid.com/docs/API_Reference/Webhooks/event.html

<img width="976" alt="screen shot 2018-03-23 at 11 52 56 am" src="https://user-images.githubusercontent.com/8733663/37815476-cf6f72fa-2e90-11e8-9d0e-6305a2edd782.png">

**Comment by zeeshangulzar** [comment]
I have reviewed the header file in your code and found the solution

`uniq_args({ user_id: 1.id, user_name: 'Test' })`

You have developed a wonderful gem, but we don't have detailed documentation. I'll try to create a PR for Readme.md after my current project

**Comment by paveltyk** [comment]
@zeeshangulzar yes, `uniq_args` is the way to go. I will highly appreciate PR to improve docs.
